### ISSUE TITLE
Broken VLS-128 config

### ISSUE THREAD

**Issue by flopie2009** [valgur/velodyne_decoder#2]
While testing the VLS-128 integration, the reading of the rosbag failed with:

`File "*****/python3.6/site-packages/velodyne_decoder/__init__.py", line 94, in read_bag
    decoder = ScanDecoder(config)
RuntimeError: Unable to open calibration file: ******/python3.6/site-packages/velodyne_decoder/calibrations/VLS-128.yml`

This is because the config file within the repo is broken and some of the laser id's have missing data. Is it possible to fix this issue?

**Comment by valgur** [comment]
Indeed, the original VLS-128 XML calibration file from VeloView is already kind of weird. The [VLS-128.xml](https://gitlab.kitware.com/LidarView/velodyneplugin/-/blob/0cddc1f92e69b7b26ffc5619aceb1c00854442e6/CalibrationsFiles/VLS-128.xml#L1577) calibration XML is identical to the [Alpha Prime.xml](https://gitlab.kitware.com/LidarView/velodyneplugin/-/blob/0cddc1f92e69b7b26ffc5619aceb1c00854442e6/CalibrationsFiles/Alpha%20Prime.xml#L1576) except for the beam IDs appearing to be out of order and quite random.
The ROS driver, that this package is based on, also ships a [VLS-128 config](https://github.com/ros-drivers/velodyne/blob/master/velodyne_pointcloud/params/VLS128.yaml#L387) that is almost identical to the Alpha Prime config generated from the VeloView XML. The only difference, albeit an important one, is the `distance_resolution` parameter being 0.007 meters in the ROS config instead of 0.004 in the one generated from VeloView. Could you please verify that the point clouds decoded with the Alpha Prime calibration parameters from this repo have the correct scale?

Based on the above I will simply drop the VLS-128.yml file and deprecate the `VLS-128` model ID option in favor of `Alpha Prime`. They appear to be virtually identical as far as I know.

**Comment by flopie2009** [comment]
I checked again the scale of the Alpha Prime pointcloud compared to a VLP-32 pointcloud. And both looked as expected. Resulting, the scale seems to be fine.
